M40 answersheets
moodleou/moodle-quiz_answersheets pull request #34
Opened 2022-03-29 10:35 UTC by mkassaei

This is now ready for review.

2022-03-29 15:58 UTC, timhunt commented
Thanks Mahmoud. This looks almost ready to go. I just spotted a very few minor things. See the review comments above.

2022-03-30 09:15 UTC, timhunt requested changes

2022-03-30 09:15 UTC, timhunt commented on .github/workflows/ci.yml
> +        run: moodle-plugin-ci behat --profile chrome
I'm curious. What was the issue which required you to specify chrome?

2022-03-30 09:15 UTC, timhunt commented on .github/workflows/ci.yml
> +#          node-version: '16.14.1'
We don't really want commented out stuff left in the file. With latest moodle-plugin-ci, you can acutally delete the entire Install node step, so that is the best way to fix this.

2022-03-30 09:15 UTC, timhunt commented on changes.md
> +* Does not support custom user profile fields.
Wow! we must have missed this. We can fix this in a future version.

I wonder if this bullet point would be better merged with the next one? Something like

Replaced uses of deprecated user fields functions. (Note, this plugin does not yet support the display of custom profile fields.

2022-03-30 09:15 UTC, timhunt commented on version.php
>  $plugin->requires  = 2018120300;
This was wrong before, but it would be good to fix it now. If 3.9 is our lowest supported version, which it is, this should be 

$plugin->requires  = 2020061500.

Or, if we are increasing minimum supported version to 3.11, this needs to be 2021051700, and we need to update $plugin->release below.

2022-03-30 09:15 UTC, timhunt commented on .github/workflows/ci.yml
> -            database: 'mariadb'
Remind me. What goes wrong with the tests which means it is hard to support 3.9 and 3.10?

2022-03-30 10:40 UTC, mkassaei commented on .github/workflows/ci.yml
> -            database: 'mariadb'
Thanks Tim for your comments. I have just incorporated all suggested, including adding correction of $plugin->requires = 2020061500 for 3.9+. The question is, do we actually need to support 3.9 and 3.10 with php 7.2 and 7.3 respectively?

2022-03-30 10:43 UTC, mkassaei commented on .github/workflows/ci.yml
> -            database: 'mariadb'
Only some behat tests failing in 3.9 and 3.10 (see: [here](https://github.com/mkassaei/moodle-quiz_answersheets/runs/5751789633?check_suite_focus=true) )

2022-03-30 10:51 UTC, timhunt commented on .github/workflows/ci.yml
> -            database: 'mariadb'
Right, it is the use field stuff from Moodle 3.11 that we need. That is a good reason to only support 3.11 and master, so we should do that. (Those are the only version that Moodle HQ support. It is only worth trying to support older versions if we can do it with minimal hassle.)

2022-03-30 11:42 UTC, mkassaei commented on .github/workflows/ci.yml
> -            database: 'mariadb'
Thanks Tim, I'll change this and push it again.

2022-04-04 10:30 UTC, merged

2022-04-04 10:31 UTC, timhunt commented
Thanks Mahmoud.